apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-svc
  labels:
    app: coordinator-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator-svc
  template:
    metadata:
      labels:
        app: coordinator-svc
    spec:
      containers:
      - name: coordinator
        image: workers-poc/coordinator
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1G"
            cpu: "500m"
        ports:
          - containerPort: 8000
        envFrom:
        - configMapRef:
            name: azure-config

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: coordinator-svc-destination-rule
spec:
  host: coordinator-svc
  trafficPolicy:
    loadBalancer:
      simple: RANDOM

---

apiVersion: v1
kind: Service
metadata:
  name: coordinator-svc
spec:
  selector:
    app: coordinator-svc
  ports:
    - port: 8000
      name: http